name: Main

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened]

env:
    KOSLI_FLOW: sonarcloud-webhook
    KOSLI_TRAIL: trail-test
    KOSLI_ARTIFACT_FINGERPRINT: 5bb56d5eb9f4fc31fb8d0f368fa1ac076d777dda3742557ab9db2df6e38e149e

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.analysis.kosli_flow=${{ env.KOSLI_FLOW }}
            -Dsonar.analysis.kosli_trail=${{ env.KOSLI_TRAIL }}
            -Dsonar.analysis.kosli_artifact_fingerprint=${{ env.KOSLI_ARTIFACT_FINGERPRINT }}
